export const GET_DYNAMIC_NAME = "GET_DYNAMIC_NAME";
export const GET_ALL_CODES = "GET_ALL_CODES";

// PART CONST
export const PART = {
  LOADING: "PART_LOADING",
  SUCCESS: "PART_SUCCESS",
  FAILED: "PART_FAILED",
};

export const CODE = {
  LOADING: "CODE_LOADING",
  SUCCESS: "CODE_SUCCESS",
  FAILED: "CODE_FAILED",
};

export const MODAL = {
  LOADING: "MODAL_LOADING",
  SUCCESS: "MODAL_SUCCESS",
  FAILED: "MODALE_FAILED",
};

export const MODBUS = {
  LOADING: "MODBUS_LOADING",
  SUCCESS: "MODBUS_SUCCESS",
  FAILED: "MODBUS_FAILED",
};
